import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { getFactions } from '../api/factions'
import { getProducts } from '../api/products'
import { useAuth } from '../context/AuthContext'
import { useShopTogether } from '../context/SessionContext'

export default function ShopTogetherSession() {
  const { code } = useParams(); const navigate = useNavigate(); const { user } = useAuth(); const together = useShopTogether(); const [name, setName] = useState(''); const [products, setProducts] = useState([]); const [factions, setFactions] = useState([]); const [faction, setFaction] = useState(''); const [selected, setSelected] = useState(null); const [error, setError] = useState('')
  useEffect(() => { const memberId = together.storedMemberId(code); if (memberId) together.load(code, memberId).catch(() => {}); else together.leaveSession() }, [code])
  useEffect(() => { if (together.myMemberId) { getFactions().then(setFactions); getProducts({ factionSlug: faction || undefined }).then(setProducts) } }, [together.myMemberId, faction])
  const subtotal = useMemo(() => together.cart.reduce((sum, item) => sum + item.qty * (item.variantId?.productId?.basePrice || 0), 0), [together.cart])
  const host = String(user?.id || user?._id) === String(together.session?.hostUserId)
  if (together.ended) return <main className="p-4"><p>This session has ended.</p><Link to="/shop">Back to shop</Link></main>
  if (together.error === 'not-found') return <main className="p-4"><p>Session not found.</p><Link to="/shop-together">Back to Shop Together</Link></main>
  if (!together.myMemberId) return <main className="mx-auto max-w-md p-4"><h1 className="text-2xl font-semibold">Enter your name to join</h1><form className="mt-4 space-y-3" onSubmit={async (e) => { e.preventDefault(); try { await together.join(code, name) } catch (err) { setError(err.response?.data?.message || 'Could not join') } }}><input className="block w-full border p-2" value={name} onChange={(e) => setName(e.target.value)} required /><button className="border px-4 py-2">Join</button></form>{error && <p>{error}</p>}</main>
  return <main className="mx-auto max-w-5xl space-y-6 p-4"><h1 className="text-2xl font-semibold">Shop Together: {code}</h1><section><h2 className="font-semibold">Members</h2><div className="flex gap-2">{together.members.map((member) => { const active = Date.now() - new Date(member.lastSeenAt).getTime() < 10000; return <span key={member._id} className={active ? 'border p-2' : 'border p-2 text-neutral-400'}>{member.displayName}{String(together.session.hostUserId) === String(member.userId) ? ' (Host)' : ''}{active ? ' • active' : ' • away'}</span> })}</div></section><section><h2 className="font-semibold">Shared cart</h2>{together.cart.map((item) => { const product = item.variantId.productId; return <div className="flex gap-3 border p-2" key={item._id}><span className="flex-1">{product.name} — {product.factionId.name} — {item.variantId.size}/{item.variantId.color}<br />Added by {item.addedBy.displayName}</span><button onClick={() => together.updateSharedCartQty(item._id, item.qty - 1)}>−</button><span>{item.qty}</span><button onClick={() => together.updateSharedCartQty(item._id, item.qty + 1)}>+</button><button onClick={() => together.removeSharedCartItem(item._id)}>Remove</button><span>₹{item.qty * product.basePrice}</span></div> })}<p className="mt-2 font-semibold">Subtotal: ₹{subtotal}</p></section><section><h2 className="font-semibold">Add items</h2><select value={faction} onChange={(e) => setFaction(e.target.value)}><option value="">All factions</option>{factions.map((f) => <option key={f._id} value={f.slug}>{f.name}</option>)}</select><div className="grid gap-2 sm:grid-cols-3">{products.map((product) => <button className="border p-2 text-left" key={product._id} onClick={() => setSelected(product)}>{product.images?.[0] && <img className="h-20 w-full object-cover" src={product.images[0]} alt="" />}{product.name}</button>)}</div>{selected && <div className="mt-3 border p-3"><p>{selected.name}</p>{selected.variants.map((variant) => <button className="mr-2 border p-1" key={variant._id} onClick={() => together.addToSharedCart(variant._id, 1)}>{variant.size}/{variant.color}</button>)}</div>}</section>{host ? <div className="flex gap-3"><button className="border px-4 py-2" onClick={() => navigate(`/checkout?session=${code}`)}>Checkout</button><button className="border px-4 py-2" onClick={() => together.endSession()}>End session</button></div> : <p>Waiting for the host to check out.</p>}<button onClick={() => { together.leaveSession(); navigate('/shop-together') }}>Leave session</button></main>
}
